 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  language_ground: # name of the dataset builder
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: /projectnb2/ivc-ml/aburns4/mug/train_10.json
          storage: /projectnb2/ivc-ml/aburns4/mug/train_10.json
        val:
          url:  /projectnb2/ivc-ml/aburns4/mug/eval_1.json
          storage:  /projectnb2/ivc-ml/aburns4/mug/eval_1.json
        test:
          url: /projectnb2/ivc-ml/aburns4/mug/test_1.json
          storage: /projectnb2/ivc-ml/aburns4/mug/test_1.json
      images:
        storage: /projectnb2/ivc-ml/aburns4/combined/
